{
    'name': 'Stoke Operation',
    "summary": "Internal operations for stock",
    "version": "17.0.1.1.1",
    "license": "LGPL-3",
    'author': 'Droga ERP Team',
    'website': '',
    "category": "Warehouse Management",
    'depends': ['base', 'product','stock','purchase','custom_purchase_order','eg_vendor_type'],
    'data': [
        'data/stock_request_sequence_data.xml',
        'security/stock_request_security.xml',
        'security/ir.model.access.csv',
         'report/afro_stock_request.xml',
          'report/report_grn.xml',
         'report/report_don.xml',
        'report/report_request_action.xml',
        'views/transfer_note_views.xml',
        'views/delivery_order_transfer_views.xml',
        'views/good_reciving_note_transfer_views.xml',
        'views/store_request_views.xml',
        'views/purchase_order_views.xml',
        'views/store_issue_views.xml',
        'views/purchase_performa_views.xml', 
        'views/product_views.xml',
        'views/store_request_menu.xml',

    ],
    'installable': True,
    'application': True,
}
